Add TODO about features to test once we bump MSRV
We get build errors when building with Rust 1.29 for `core2` and
`schemars`. Add todos to remind us to test theses once we bump MSRV.

Note the `schemars` cannot be added to the test matrix because it must
be built with `std`, we must add a specific test for this combination.

Example build error:

```
error: unable to get packages from source

Caused by:
failed to parse manifest at `/home/tobin/.cargo/registry/src/github.com-1ecc6299db9ec823/core2-0.3.3/Cargo.toml`

Caused by:
editions are unstable

Caused by:
feature `edition` is required
```

Add a TODO to `test.sh` to remind us to add `core2` to the features
matrix once we bump MSRV.

Add a commented out schemars/std test and a note to uncomment test once
we bump MSRV past 1.29